### PR TITLE
New README.md (needs to be reviewed)

### PR DESCRIPTION
**Pull request by luigoalma**
The last line is still kind of a mess.
(Again not a native english speaker)

### CODE REVIEW

**Comment by luigoalma** [comment]
I haven't mentioned the seeddb yet.

**Comment by ihaveamac** [comment]
I'm not merging until you say it's done

**Comment by luigoalma** [comment]
I don't what this merged before it's done. So, we're both in the same page.

**Comment by ihaveamac** [comment]
I am considering moving this entire thing to the wiki instead of README, but it should be finished first. what do you think?

**Comment by luigoalma** [comment]
Moving it to the wiki? That's fine by me. I don't think there's anything else we can add to the readme so I think it's finished.

**Comment by ihaveamac** [comment]
if it's ready then I'll close the PR and move everything to the Wiki

**Comment by luigoalma** [comment]
Yeah I think it's ready, close the PR if you think it's ready too.

**Pull request closed without merging**
