### PR TITLE
Added titles.

### PR DESCRIPTION
**Pull request by luigoalma**
Added Pokemon Red, Blue and Yellow VC roms in some more languages.
It seems like Pokemon Red and Blue all have the same values independent of language (didn't check the JPN versions), same thing for Pokemon Yellow.
Also I was unsure of the region so I left as (WORLD?) in the title.

### CODE REVIEW

**Comment by ihaveamac** [comment]
as far as I know, the Pokémon VC is the same worldwide (same title ID for each version and language). so a Red english one would have the same TID for USA and EUR, etc.

**Comment by ihaveamac** [comment]
if you can quickly change "WORLD?" to "WORLD" then I can merge now.

**Comment by luigoalma** [comment]
I'll change it. Hold on a sec.

**Comment by ihaveamac** [comment]
thanks

**Comment by luigoalma** [comment]
Glad I could help. :)

**Pull request merged**
