### PR TITLE
Added more titles.

### PR DESCRIPTION
**Pull request by luigoalma**
000400000014D900 = Gravity Falls Legend of the Gnome Gemulets (EUR)
0004000000168900 = Garfield Kart (EUR)
0004000000168E00 = Paddington: Adventures in London (EUR)
000400000017AF00 = The Peanuts Movie: Snoopy's Grand Adventure (EUR)

I don't need to create a pull request so early, but I'm doing it anyway.

### CODE REVIEW

**Comment by luigoalma** [comment]
Hey @ihaveamac, how far would you say we are from finishing this? I would say still kind far.
Considering the size of the Seeddb title list you liked at the issue page.

**Comment by ihaveamac** [comment]
technically I could probably say that this will be over once Nintendo stops supporting the 3DS, or *hax can find these offsets itself.

I try to go in order of what games might be worth my time, or which games are more likely to be useful to generate an xml for. but that's just me.

**Comment by luigoalma** [comment]
Ok. I have been decrypting more the smaller roms, because I have a mess of files on my disk, I don't know what to delete, and have ~10GB of free space.

**Comment by luigoalma** [comment]
But at least that script you modified makes things a lot easier with my disk space situation too.

**Pull request merged**
