### PR TITLE
Added 2 more titles.

### PR DESCRIPTION
**Pull request by luigoalma**
0004000000160C00 = Project X Zone 2 (USA)
0004000000162000 = Project X Zone 2 (EUR)

Finished decrypting. (I should stop decrypting full roms and only decrypt exefs)

### CODE REVIEW

**Comment by ihaveamac** [comment]
don't know how you can not decrypt full roms, but if they're CIAs, you could probably get away with just doing CXI only. haven't tried it though.

**Comment by luigoalma** [comment]
I could use ncchinfo_gen.py and strip off anything that isn't for the exefs decryption from the ncchinfo.bin

**Comment by ihaveamac** [comment]
well I've clearly never used that, I should probably figure it out some time.

**Comment by luigoalma** [comment]
I may try to remove the part of the script that isn't for exefs.
But anyway, I have to go.

**Comment by ihaveamac** [comment]
https://gist.github.com/ihaveamac/304bb69e98fc4ce2d5c9

this is modified to not generate xorpads for romfs, but leaves in exheader and exefs. it's also modified to save in the current working directory and not just where the .py script is. I tested an ncchinfo.bin generated using this with Decrypt9, and it worked as expected.

**Comment by ihaveamac** [comment]
modified it again to only generate exefs xorpads.

**Comment by luigoalma** [comment]
I have returned and I see you modified ncchinfo_gen.py to only generate exefs, this will make everything a lot more quicker.
Sorry I could help in the making of that script, I wasn't available.

**Comment by ihaveamac** [comment]
it wasn't that much to change really, just disabling things that process exhdr/romfs and things.

**Comment by luigoalma** [comment]
I saw you commented the parts of exhdr and romfs and added a return in some other parts.

**Comment by ihaveamac** [comment]
the returns are there so it doesn't reach an error (https://gist.github.com/ihaveamac/304bb69e98fc4ce2d5c9#file-ncchinfo_gen_exefs-py-L223-L225) and also because python would complain if nothing was there I think (needed indents?).

**Comment by luigoalma** [comment]
I don't know enough python to confirm that. I'm always checking the python docs when I experiment with it.

**Comment by ihaveamac** [comment]
well it works as intended, so I'm not going to bother with it for now

**Comment by luigoalma** [comment]
If works as intended, then there's no need to bother with it.

**Comment by luigoalma** [comment]
Hey @ihaveamac, I have a little problem, it's the fact that I don't know how to decrypt the exefs using the xorpads, I only know how to use xorpads on xorer to decrypt 3ds roms, but just decrypting the exefs makes the program crash.
Could you help me with this problem?

**Comment by ihaveamac** [comment]
this is how I've been doing it...

first, extract the executable (cxi):

```
3dstool -xvt0f cci 0.cxi game.3ds
```

next, use the xorpad to extract the exefs:

```
3dstool -xvtf cxi 0.cxi --exefs exefs.bin --exefs-xor 000400000XXXXX00.Main.exefs_norm.xorpad
```

if you have `000400000XXXXX00.Main.exefs_7x.xorpad` then you need to do this:

```
3dstool -xvtf cxi 0.cxi --exefs exefs.bin --exefs-xor 000400000XXXXX00.Main.exefs_norm.xorpad --exefs-top-xor 000400000XXXXX00.Main.exefs_7x.xorpad
```

then, I use ctrtool to extract the exefs:

```
ctrtool -t exefs --exefsdir=exefs --decompresscode exefs.bin
```

**Comment by luigoalma** [comment]
That worked, thanks.
Also, ncchinfo_gen_exefs.py makes everything a LOT more quicker.

**Pull request merged**
